[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 48
truncate_to_repo = false
truncation_symbol = "…/"

[aws]
format = '/ [aws ($profile )(\($region\) )]($style)'
style = "bold blue"

[aws.region_aliases]
ap-northeast-1 = "jp"

[gcloud]
format = '/ [gcloud \($project\)]($style) '

[docker_context]
format = "via [docker $context](blue bold)"

[git_branch]
format = '/ [git \($branch(:$remote_branch)\)]($style) '
truncation_length = 32
truncation_symbol = '...'

[golang]
disabled = true
# format = 'via [go ($version )($mod_version )]($style)'
