name: lint

on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: lint
    runs-on: 
      labels: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: msg
        run: |
          echo "::warning file=assets/sample.json,line=4,endLine=4,col=1,endColumn=2,title=message-title::Hello World, Meguru"
